import type { Metadata } from "next";
import { Roboto, Space_Grotesk } from "next/font/google";
import { BookingDrawer } from "./components/booking/BookingDrawer";
import { BookingProvider } from "./components/booking/BookingProvider";
import { SmoothScroll } from "./components/SmoothScroll";
import { listConfirmedUnavailableDates } from "@/lib/bookings/repository";
import "./globals.css";

const roboto = Roboto({
  weight: "500",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto-face",
});

const spaceGrotesk = Space_Grotesk({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-space-grotesk-face",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let unavailableDateKeys: string[] = [];
  try {
    unavailableDateKeys = await listConfirmedUnavailableDates();
  } catch (error) {
    console.error("Failed to load confirmed unavailable dates", error);
  }

  return (
    <html lang="en" className={`h-full antialiased ${roboto.variable} ${spaceGrotesk.variable}`}>
      <body className="min-h-full flex flex-col font-primary">
        <SmoothScroll>
          <BookingProvider>
            {children}
            <BookingDrawer unavailableDateKeys={unavailableDateKeys} />
          </BookingProvider>
        </SmoothScroll>
      </body>
    </html>
  );
}
